apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat 
  labels: 
    app: tomcat
    name: tomcat-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: tomcat
  template: 
    metadata: 
      labels: 
        app: tomcat
    spec: 
      containers: 
        - image: anilpu3/cicd-build-docker-repo:1.0
          name: tomcat
          volumeMounts: 
            - mountPath: /usr/local/tomcat/webapp
              name: bindvolume
      volumes: 
        - name: bindvolume
          hostPath: 
            path: /root/bindVolume
            type: Directory 
           
